#!/bin/bash

# Use set -euo pipefail to make the script more robust
set -euo pipefail

# Use a function to avoid repeating code
print_icon() {
  local icon="$1"
  local pattern="$2"
  local interface=$(echo "$IF" | grep -E "^$pattern")
  if [ -n "$interface" ] && ip link show "$interface" | grep -q 'state UP'; then
    echo "$icon"
  fi
}



# Use a variable to avoid repeating the grep pattern
IF_PATTERN='^(wlo|enp)'

# Use command substitution instead of echo | wc -l
IF=$(ip link show | awk '/state UP/ && $2 ~ pattern {print $2}' pattern="$IF_PATTERN" | sed 's/://g')
IF_NUM=$(echo "$IF" | wc -l)


if [ "$IF_NUM" -eq 0 ]; then
  STATUS=""
else
  print_icon "󰖩" elo
  print_icon "󰈀" enp
fi
