#!/bin/bash

# Update package list
sudo pacman -Syy

# Check for available updates and print package names with versions (filter for kernel updates and formats them in bold red tex)
pacman -Qu | awk '/^linux/ {print "\033[1;31m" $1 " -> " $2 "\033[0m"} !/^linux/ {print $1 " -> " $2}' | sed '/^\s*$/d'
