#!/bin/sh

# This script examines whether a new kernel update is included in the available package updates. 
# If a new kernel update is detected, it displays a package symbol accompanied by a small plus sign. 
# Otherwise, it shows the same symbol without the plus sign, indicating that only 'normal' package updates are currently available.

check=$(checkupdates --nocolor)
num_packages=$(checkupdates | wc -l)

# Check if the search pattern (new kernel) is present in the output using grep with extended regex
if grep -qE "linux [0-9]+\.[0-9]+\.[0-9]+\S+ -> [0-9]+\.[0-9]+\.[0-9]+\S+" <<< "$check"; then
    printf "󱧘 %s" "$num_packages"
elif [ "$num_packages" -eq 0 ]; then
    printf "󰏗"
elif [ "$num_packages" -gt 0 ]; then
    printf "󰏖 %s" "$num_packages"
fi
