#!/bin/bash

SINK=$(pactl get-default-sink) 

case "$1" in
    "up")
        pactl set-sink-volume $SINK +5%
        ;;
    "down")
        pactl set-sink-volume $SINK -5%
        ;;
    "mute")
        pactl set-sink-mute $SINK toggle
        mute_status=$(pactl get-sink-mute $SINK | awk '{print $2}')
        if [ "$mute_status" = "yes" ]; then
            notify-send 'Audio Muted'
        else
            notify-send 'Audio Unmuted'
        fi
        ;;
    *)
        echo "Usage: $0 {up|down|mute}"
        exit 1
        ;;
esac

# Optionally, display the current volume using notify-send
VOLUME=$(pactl get-sink-volume $SINK | awk '{printf "%s", $5}')
notify-send "Volume: $VOLUME"

